### ISSUE TITLE
how can this module be used decently?

### ISSUE THREAD

**Issue by ghost** [fewieden/MMM-Modal#17]
Platform (Hardware/OS): Windows 10

Node version: 16

MagicMirror version: 2.17.1

Module version: develop

Description of the issue: I think the use of the mode is not sufficiently explained.

I make my modal:

```
this.sendNotification("OPEN_MODAL", {
	template: "templates/MyModal.njk",
	data: {
		title: "Test modal",
		message: "Test message"
	},
	options: {
		isDialog: true
	}
});
```
and MyModal.njk:
```
<h2 class="bright">{{data.title}},</h2>
<p>{{data.message}}</p>
```
in console I get this:

`nunjucks.min.js:4 GET http://localhost:8081/modules//modal/templates/modal.njk?s=1634300311396 404 (Not Found)`
I have only one question, how can this module be used decently?
If this is possible…

**Comment by ghost** [comment]
I guess it was tested though for me is working only if I rename MyModal.njk to modal.njk. Anyway I don’t want to comment more about this module.

**Comment by fewieden** [comment]
@hangorazvan I created an MVP for you.

The template is matching your template:
```njk
<h2 class="bright">{{data.title}},</h2>
<p>{{data.message}}</p>
```
The custom module that wants to trigger a modal 5 seconds after the MagicMirror is ready:
```js
Module.register("MyModule", {
	notificationReceived(notification) {
		if (notification === "ALL_MODULES_STARTED") {
			setTimeout(() => {
				console.log('opening modal');
				this.sendNotification("OPEN_MODAL", {
					template: "templates/MyModal.njk",
					data: {
						title: "Test modal",
						message: "Test message"
					},
					options: {
						isDialog: true
					}
				});
			}, 5000);
		}
	}
});
```
Folder structure:
![folder-structure](https://user-images.githubusercontent.com/9334168/137768293-1b53ddad-ccf8-4f10-a741-190e5ef200f6.png)

Config:
```js
{
  module: "MyModule",
  position: "top_right"
},
{
  module: 'MMM-Modal',
  position: 'fullscreen_below',
  config: {
    timer: false,
    touch: true
  }
}
```

Result:
![example](https://user-images.githubusercontent.com/9334168/137768460-c3497ff7-f062-48b5-8b36-76c10893b477.png)

**Comment by ghost** [comment]
Thank you but for now I gave up using this module.
